version: '3.8'

services:
  # --- Infrastructure Services ---
  mysql:
    image: mysql:8.0
    container_name: libhub_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  consul:
    image: consul:1.13
    container_name: libhub_consul
    ports:
      - "8500:8500"

  # --- Application Services ---
  userservice:
    build:
      context: src/LibHub.UserService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${USER_DB_CONNECTION_STRING}
      - ServiceDiscovery__ConsulAddress=http://consul:8500
    depends_on:
      - mysql
      - consul

  catalogservice:
    build:
      context: src/LibHub.CatalogService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${CATALOG_DB_CONNECTION_STRING}
      - ServiceDiscovery__ConsulAddress=http://consul:8500
    depends_on:
      - mysql
      - consul

  loanservice:
    build:
      context: src/LibHub.LoanService
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${LOAN_DB_CONNECTION_STRING}
      - ServiceDiscovery__ConsulAddress=http://consul:8500
    depends_on:
      - mysql
      - consul

  apigateway:
    build:
      context: src/LibHub.ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - userservice
      - catalogservice
      - loanservice
      - consul

volumes:
  mysql_data: